Add data science notebook image
opendatahub-io/notebooks pull request #13
Opened 2022-10-17 13:41 UTC by atheo89

Added data science notebook image

## Description
Files that have been added:
- Dockerfile
- Kustomize objects
- requirment.in 

Files that have been modified:
- Makefile

## How Has This Been Tested?
`podman run -it --rm -p 8888:8888 quay.io/opendatahub/notebooks:jupyter-data-science-ubi8-python-3.8-b0904df-dirty`

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2022-10-18 15:07 UTC, samuelvl commented
/test all

2022-10-18 15:35 UTC, samuelvl requested changes

2022-10-18 15:35 UTC, samuelvl commented on jupyter/datascience/ubi8-python-3.8/Dockerfile
> +      fix-permissions /opt/app-root -P
This should happen after `pip install`

2022-10-18 15:35 UTC, samuelvl commented on jupyter/datascience/ubi8-python-3.8/requirements.in
> +nbdime==3.0.0
`jupyterlab-git` and `nbdime` are already included in the minimal notebook image, no need to include them twice

2022-10-18 15:35 UTC, samuelvl commented on jupyter/datascience/ubi8-python-3.8/requirements.in
> +# JupyterLab extensions
Some extensions from the ODS CI framework are missing. See https://github.com/red-hat-data-services/ods-ci/blob/master/tests/Tests/500__jupyterhub/plugin-verification.robot#L17

2022-10-18 15:35 UTC, samuelvl commented on Makefile
> +jupyter-datascience-ubi8-python-3.8: jupyter-minimal-ubi8-python-3.8
Documentation in README.md is missing for this new notebook

2022-10-19 07:18 UTC, atheo89 commented
Thanks for the review! I rebased my local repo to apply your comments. About the extensions from the ODS CI framework, the `jupyterlab_requirments` is missing on the old minimal image. I have added it now.

2022-10-19 08:40 UTC, samuelvl requested changes

2022-10-19 08:40 UTC, samuelvl commented on Makefile
> +		base/ubi8-python-3.8/requirements.in jupyter/datascience/ubi8-python-3.8/requirements.in,\
We have to include `jupyter/minimal/ubi8-python-3.8/requirements.in` too.

2022-10-19 08:43 UTC, samuelvl commented
@atheo89 

> About the extensions from the ODS CI framework, the jupyterlab_requirments is missing on the old minimal image. I have added it now.

What do you mean? I can't find the `jupyterlab_requirements` package in the old minimal notebook:

```shell
$ podman run --rm quay.io/modh/odh-minimal-notebook-container:v1.17.0-9 pip show jupyterlab-requirements
WARNING: Package(s) not found: jupyterlab-requirements

$ podman run --rm quay.io/modh/odh-minimal-notebook-container:v1.17.0-9 pip show jupyterlab_requirements
WARNING: Package(s) not found: jupyterlab_requirements
```

2022-10-19 09:06 UTC, atheo89 commented
Sorry, I wasn't clear before, I added the `jupyterlab_requirements` into the [requirements.in ](https://github.com/atheo89/notebooks/blob/02586a49f3ca3217754db22638b7359d6c23257e/jupyter/datascience/ubi8-python-3.8/requirements.in#L11) in the new data science notebook image because it exists into [ods-ci](https://github.com/red-hat-data-services/ods-ci/blob/master/tests/Tests/500__jupyterhub/plugin-verification.robot#L17) Should I leave it or exclude it?

2022-10-19 10:45 UTC, samuelvl commented on README.md
> +make jjupyter-datascience-ubi8-python-3.8
Small typo `s/jjupyter/jupyter`

2022-10-20 12:18 UTC, merged