dropped z stream from python version in notebook
opendatahub-io/notebooks pull request #144
Opened 2023-07-14 18:26 UTC by dibryant

## Description

I have added` “cut -d '.' -f-2)”` to the original code  `"RUN sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json"
`in order to resolve the problem of the .z stream showing within the python version in  JL. 
## How Has This Been Tested?

https://github.com/opendatahub-io/notebooks/issues/49#issuecomment-1631234455
![Screenshot 2023-07-13 at 3 52 24 PM (2)](https://github.com/opendatahub-io/notebooks/assets/135062655/f6cfd46e-dcdc-4f0f-b4ab-e5bc676aed57)
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-07-14 19:46 UTC, harshad16 commented
/retest-required

2023-07-19 14:11 UTC, atheo89 commented
Built & run the minimal notebook and works as expected 
/lgtm 

![image](https://github.com/opendatahub-io/notebooks/assets/42587738/da00af00-3796-4583-9ad7-fd30f908468c)

2023-07-19 16:02 UTC, harshad16 requested changes
thanks for the work.
One change is needed

2023-07-19 16:02 UTC, harshad16 commented on jupyter/pytorch/ubi9-python-3.9/Dockerfile
> +    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2s)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json
```suggestion
    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json
```

2023-07-21 09:53 UTC, atheo89 commented
/retest-required

2023-07-24 19:42 UTC, harshad16 approved these changes
Thanks for the fix.

/lgtm
/approve

:100:

2023-07-24 21:02 UTC, harshad16 commented
/test all

2023-07-25 04:16 UTC, harshad16 commented
/test notebooks-e2e-tests

2023-07-25 20:55 UTC, merged