Include notebook imagestream manifests to notebook repos
opendatahub-io/notebooks pull request #186
Opened 2023-08-24 19:40 UTC by harshad16

Include notebook imagestream manifests to notebook repos

## Description

This is to reference notebook imagestream rates. 
Related-to: https://github.com/opendatahub-io/notebooks/issues/185

Copied from: https://github.com/opendatahub-io/odh-manifests/tree/master/notebook-images

## How Has This Been Tested?

compare the https://github.com/opendatahub-io/odh-manifests/tree/master/notebook-images and the files changed.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-09-01 09:47 UTC, atheo89 requested changes

2023-09-01 09:47 UTC, atheo89 commented on .github/workflows/notebooks-digest-updater-upstream.yaml
> +        description: "Provide the name of the branch you want to update ex main, vx.xx etc"
A small change. Could we consider updating the notation from `vx.xx` to `YYYYx` in the description to align it with the repository's structure?

2023-09-11 13:00 UTC, harshad16 commented on .github/workflows/notebooks-digest-updater-upstream.yaml
> +        description: "Provide the name of the branch you want to update ex main, vx.xx etc"
Thanks for the suggestion.
Made the change.

2023-09-12 09:35 UTC, atheo89 commented
Thank you for integrating this into the notebooks repository and implementing the recommended adjustments! This brings us one step closer to addressing the remaining item on https://github.com/opendatahub-io/architecture-decision-records/pull/16.

Regarding the failing tests, it's worth noting that they are not directly linked to the changes made in this PR. Instead, they are a consequence of an unmerged PR (trusty) and a known issue related to the Anaconda notebook. Given this, I recommend proceeding with the merging of this specific PR.

/lgtm

2023-09-12 12:13 UTC, harshad16 commented
Thanks for the details about the CI.
Merging this in manually for now.

2023-09-12 12:13 UTC, merged

2023-09-13 11:08 UTC, zdtsw commented
does it mean I can mark 

Workbenches | opendatahub-io/notebooks | main | Yes
-- | -- | -- | --

in [ADR](https://github.com/opendatahub-io/architecture-decision-records/pull/16)

2023-09-13 12:39 UTC, harshad16 commented
@zdtsw yes correct, now we have the manifests in the repo.
I will comment on the ADR as well.