Add tests for TrustyAI Notebooks
opendatahub-io/notebooks pull request #244
Opened 2023-10-06 14:42 UTC by dibryant

Fixes for #182 
## Description

Run Jupyter TrustyAI Notebooks for both the versions of Python, i.e 3.8 and 3.9. Run the test notebooks in the relevant environment. The tests should execute with all passing.
## How Has This Been Tested?

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-10-06 14:51 UTC, atheo89 commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebooks.ipynb
> +    "        score = statistical_parity_difference(privileged=nobias_privileged,\n",
I would suggest using a check here to evaluate the result of the score like:
```
self.assertTrue(score >= 0.0036255104824703954)  
        print("On the test_fairness_metrics test case the statistical_parity_difference score for this dataset is between the threshold [-0.1,0.1], which classifies the model as reasonably fair.")
```

2023-10-06 14:52 UTC, atheo89 commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebooks.ipynb
> +    "        self.assertEqual(actual_major_minor, expected_major_minor, \"incorrect version\")\n",
Needs a single line here

2023-10-06 14:57 UTC, atheo89 commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebooks.ipynb
> +   "outputs": [
We don't need the `outputs` metadata. 
To remove them, once you run the notebook and all tests passed, restart the Kernel of the notebook, then copy-paste it into your test_notebook.ipynb

2023-10-06 16:17 UTC, atheo89 commented on jupyter/trustyai/ubi8-python-3.8/test/test_notebooks.ipynb
> +   "display_name": "Python 3.9",
This notebook is for ubi8 flavor, so it needs to be changed to 3.8.
To do that you need to run the contents of the notebook on a ubi8 flavor (In order to be corrected automatically)

2023-10-06 16:44 UTC, atheo89 commented
/retest

2023-10-06 16:46 UTC, atheo89 commented
/test all

2023-10-06 17:26 UTC, atheo89 commented
/lgtm

2023-10-11 03:47 UTC, harshad16 requested changes
Thank for the work
can you please squash all the commit to 1 please.

2023-10-11 07:38 UTC, rkpattnaik780 commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebooks.ipynb
> +{
nit: can we rename the test notebooks to `test_notebook.ipynb` to keep it consistent with naming of other test notebooks we have.

2023-10-13 19:25 UTC, jstourac reviewed
One coment, otherwise LGTM.

2023-10-13 19:25 UTC, jstourac commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
> +   ],
I don't understand this deeply yet, but suppose that we can left the outputs field empty?

```suggestion
   "outputs": [],
```

2023-10-13 21:00 UTC, jstourac requested changes

2023-10-13 21:00 UTC, jstourac commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
> +    "     def test_fairnessmetrics(self):\n",
Indentation:

```suggestion
    "    def test_fairnessmetrics(self):\n",
```

2023-10-16 15:45 UTC, atheo89 commented
Upon reviewing the test notebook for the Ubi9, it appears to be distinct from the one I examined during my previous review.  Could you please revert it? 
It should look like the ubi8 -> https://github.com/dibryant/notebooks/blob/trustyai/jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb

2023-10-16 15:47 UTC, atheo89 requested changes
Some changes are required

2023-10-16 15:47 UTC, atheo89 commented on jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
> +{
Upon reviewing the test notebook for the Ubi9, it appears to be distinct from the one I examined during my previous review. Could you please revert it?
It should look like the ubi8 -> https://github.com/dibryant/notebooks/blob/trustyai/jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb

2023-10-16 19:45 UTC, atheo89 commented
/retest-required

2023-10-17 07:36 UTC, atheo89 commented
/test notebooks-e2e-tests

2023-10-17 07:58 UTC, atheo89 commented
/test notebooks-e2e-tests

2023-10-17 10:05 UTC, atheo89 commented
The e2e is normal that it failed on TrustyAI step this is because is not yet merged into the main -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_notebooks/244/pull-ci-opendatahub-io-notebooks-main-notebooks-e2e-tests/1714189236862717952

2023-10-17 10:08 UTC, atheo89 commented
/override ci/prow/notebooks-e2e-tests 
/approve
/lgtm

2023-10-17 11:01 UTC, atheo89 commented
/override ci/prow/notebooks-e2e-tests
/override ci/prow/images

2023-10-17 11:03 UTC, merged