Add Habana 1.13 notebook
opendatahub-io/notebooks pull request #380
Opened 2023-12-21 17:38 UTC by Xaenalt

Habana currently added support for OpenShift 4.12.43 to their 1.13 driver series

Hopefully I did this update correctly

2024-01-03 14:56 UTC, Xaenalt commented
@harshad16 any idea what I'm doing wrong in the linting here?

2024-01-03 14:58 UTC, harshad16 commented
> any idea what I'm doing wrong in the linting here?

@Xaenalt I don't think you are doing anything wrong.
Its more to do with something from the past
i will take a look.

2024-03-19 10:51 UTC, atheo89 requested changes
Thank you @Xaenalt for your pull request!
I added a comment for a small change that is needed.

2024-03-19 10:51 UTC, atheo89 commented on habana/1.13.0/ubi8-python-3.8/Pipfile
> +# Parent image requirements to maintain cohesion
The packages from line 33 to 58 have been updated to newer versions, could you take a look and update  this file as well? Ref link: https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi8-python-3.8/Pipfile#L9-L45

2024-03-20 15:52 UTC, harshad16 commented on habana/1.13.0/ubi8-python-3.8/Pipfile
> +# Parent image requirements to maintain cohesion
Lets get this in , and include the changes in a separate PR.

2024-03-20 15:53 UTC, merged