ci: increase available disk space for GHA container image builds
opendatahub-io/notebooks pull request #577
Opened 2024-06-21 07:45 UTC by jiridanek

## Description

This PR creates a LVM overlay, increasing the available disk space for podman builds from previous 66GB

```
/dev/sda1        74G  4.1G   66G   6% /mnt
```

to 83GB by default,

```
/dev/mapper/buildvg-buildlv   83G   24K   83G   1% /home/runner/.local/share/containers
```

and whopping 106GB when building any amd/cude/pytorch/tensorflow image!

```
 /dev/mapper/buildvg-buildlv  106G   24K  106G   1% /home/runner/.local/share/containers
```

This should give us enough disk space to build AMD ROCm images.

## How Has This Been Tested?

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2024-06-21 07:45 UTC, jiridanek commented on ci/cached-builds/storage.conf
> +pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}
`use_hard_links = "false"` is what's shown in the blog

2024-06-21 08:47 UTC, atheo89 requested changes

2024-06-21 08:47 UTC, atheo89 commented on .github/workflows/build-notebooks-TEMPLATE.yaml
> +        if: "${{ contains(inputs.target, 'amd') || contains(inputs.target, 'cuda') || contains(inputs.target, 'pytorch') || contains(inputs.target, 'tensorflow') }}"
Maybe need to add `intel` as well

2024-06-21 08:49 UTC, jiridanek commented on .github/workflows/build-notebooks-TEMPLATE.yaml
> +        if: "${{ contains(inputs.target, 'amd') || contains(inputs.target, 'cuda') || contains(inputs.target, 'pytorch') || contains(inputs.target, 'tensorflow') }}"
It is not necessary. Everything we have currently can build with the (current) 66GB of disk space. It is only `amd` that's causing problems. I can imagine going the other way, remove everything except `amd` from here ;P

2024-06-21 08:51 UTC, jiridanek commented on .github/workflows/build-notebooks-TEMPLATE.yaml
> +        if: "${{ contains(inputs.target, 'amd') || contains(inputs.target, 'cuda') || contains(inputs.target, 'pytorch') || contains(inputs.target, 'tensorflow') }}"
Hmm, yeah, I'll add `intell`, so they aren't said we don't give them space.

2024-06-21 10:26 UTC, jiridanek commented
/label tide/merge-method-squash

2024-06-21 16:32 UTC, jiridanek commented
/retest-required

2024-06-24 10:41 UTC, jiridanek commented
/test runtimes-ubi8-e2e-tests

2024-06-26 09:41 UTC, jiridanek commented
* known issue https://github.com/opendatahub-io/notebooks/issues/562
/override ci/prow/intel-notebooks-e2e-tests

2024-06-26 11:31 UTC, atheo89 approved these changes
Thanks Jiri for this enchantment! 

/lgtm

2024-06-26 14:47 UTC, merged