RHOAIENG-12535: Setup Jupyter 4 + Elyra environment on RHOAI/ODH
opendatahub-io/notebooks pull request #701
Opened 2024-09-13 00:54 UTC by paulovmr

## Description
* Prepare the notebooks images to use the next `odh-elyra` release.
* Remove commented code for Elyra patches that are being applied directly on ODH Elyra fork [here](https://github.com/opendatahub-io/elyra/pull/34).

* To do:
  - Confirm next version for `odh-elyra` release on PyPI
  - Update lock files

## How Has This Been Tested?

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-09-16 08:33 UTC, atheo89 reviewed
/lgtm 

Just two comments to revert some comments back :slightly_smiling_face:

2024-09-16 08:33 UTC, atheo89 commented on jupyter/datascience/ubi9-python-3.11/Dockerfile
>  # TO DO: Uncomment this lines when elyra compatibility with jupyterlab 4.2 is done
Could you remove as well the comment `# TO DO: Uncomment this lines when elyra compatibility with jupyterlab 4.2 is done`

2024-09-16 08:33 UTC, atheo89 commented on jupyter/datascience/ubi9-python-3.11/Dockerfile
> +    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json && \
```suggestion
    # Replace Notebook's launcher, "(ipykernel)" with Python's version 3.x.y \
    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json && \
```
Let's keep the comment for this line :slightly_smiling_face:

2024-09-16 10:41 UTC, jiridanek commented
The CI fails are legit, please fix CI before removing the wip label.

(Just noticed we have two different wip labels in this project defined ;)

2024-09-18 10:29 UTC, paulovmr commented
/retest

2024-09-18 12:26 UTC, atheo89 commented
Hey Paulo, could you rebase this PR and update also pipfile for TrustyAI notebook?

2024-09-19 19:41 UTC, harshad16 requested changes
for rocm-tensorflow image, can you please include the 
utils file https://github.com/opendatahub-io/notebooks/tree/main/jupyter/tensorflow/ubi9-python-3.11/utils and include the Dockerfile https://github.com/opendatahub-io/notebooks/blob/1600f89300c5c0ed709fbe5d807609de397a3b83/jupyter/tensorflow/ubi9-python-3.11/Dockerfile#L23C13-L23C84
so that those change can be fixed in rocm-tensorflow.

2024-09-20 01:56 UTC, paulovmr commented
/retest

2024-09-20 11:37 UTC, paulovmr commented
/retest

2024-09-20 12:46 UTC, harshad16 approved these changes
/lgtm
/approve

Reason to approve:
- The changes bring in elyra back, so it can tested in proper manner
- The PR builds get override, if new changes are pushed, so lets get this one in.
- another note: as presubmit and postsubmit jobs get different cluster, some build would be faster in the main than in PR

2024-09-20 13:13 UTC, paulovmr commented
@jstourac Good point, since I'm rebasing it to fix conflicts, I'm also updating `odh-elyra` to use `4.0.0.dev1` version.

2024-09-20 18:07 UTC, paulovmr commented
/retest

2024-09-23 13:42 UTC, paulovmr commented
/retest

2024-09-24 09:03 UTC, atheo89 commented
/override ci/prow/images
Since it fails on ubi8 that we recently removed, the rest looks good
/override ci/prow/notebooks-ubi9-e2e-tests
/override ci/prow/rocm-notebooks-e2e-tests 
/lgtm

2024-09-24 12:28 UTC, merged