Update the amd manifest with 2024b and python 3.11
opendatahub-io/notebooks pull request #710
Opened 2024-09-25 14:17 UTC by dibryant

fixes for https://issues.redhat.com/browse/RHOAIENG-12021
## Description

updated the manifest with 2024b release info
## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-09-25 20:16 UTC, harshad16 requested changes
Please revert the change that changes the name ROCm to ROCM 
https://github.com/opendatahub-io/notebooks/commit/975a5f71f941a7f05f6c5e5a2086184ee72981dc

Rest all look good.

2024-09-26 12:04 UTC, jstourac commented on manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
> +        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.11"},{"name":"ROCM-PyTorch","version":"2.3"}]'
Is the ROCM-PyTorch verson correct here? In https://quay.io/repository/opendatahub/workbench-images/manifest/sha256:57926cbe6fb0bb8e1a1bd626ea9635ec715cd05f0e4dae91e22cbd05b0f94102?tab=packages, I can see: `torch 2.4.1`.

2024-09-26 12:04 UTC, jstourac commented on manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
> +        opendatahub.io/notebook-software: '[{"name":"ROCM","version":"6.1"},{"name":"Python","version":"v3.11"}]'
Also, AMD use `ROCm` (lower `m`) in their materials, https://www.amd.com/en/products/software/rocm.html . Is there a particular reason we don't want to follow it?

2024-09-26 12:10 UTC, jstourac commented on manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
>          opendatahub.io/notebook-python-dependencies: '[{"name":"ROCm-TensorFlow","version":"2.15"},{"name":"Tensorboard","version":"2.15"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib"
```suggestion
        opendatahub.io/notebook-python-dependencies: '[{"name":"ROCM-PyTorch","version":"2.3"},{"name":"Tensorboard","version":"2.16"},{"name":"Kafka-Python","version":"2.2"},{"name":"Matplotlib","version":"3.9"},{"name":"Numpy","version":"2.1"},{"name":"Pandas","version":"2.2"},{"name":"Scikit-learn","version":"1.5"},{"name":"Scipy","version":"1.14"},{"name":"Odh-Elyra","version":"4.0"},{"name":"PyMongo","version":"4.8"},{"name":"Pyodbc","version":"5.1"}, {"name":"Codeflare-SDK","version":"0.18"}, {"name":"Sklearn-onnx","version":"1.17"}, {"name":"Psycopg","version":"3.2"}, {"name":"MySQL Connector/Python","version":"9.0"}]'
```

2024-09-26 12:10 UTC, jstourac commented on manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
>          opendatahub.io/notebook-python-dependencies: '[{"name":"ROCm-PyTorch","version":"2.3"},{"name":"Tensorboard","version":"2.16"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib","ve
```suggestion
        opendatahub.io/notebook-python-dependencies: '[{"name":"ROCM-PyTorch","version":"2.3"},{"name":"Tensorboard","version":"2.16"},{"name":"Kafka-Python","version":"2.2"},{"name":"Matplotlib","version":"3.9"},{"name":"Numpy","version":"2.1"},{"name":"Pandas","version":"2.2"},{"name":"Scikit-learn","version":"1.5"},{"name":"Scipy","version":"1.14"},{"name":"Odh-Elyra","version":"4.0"},{"name":"PyMongo","version":"4.8"},{"name":"Pyodbc","version":"5.1"}, {"name":"Codeflare-SDK","version":"0.18"}, {"name":"Sklearn-onnx","version":"1.17"}, {"name":"Psycopg","version":"3.2"}, {"name":"MySQL Connector/Python","version":"9.0"}]'
```

2024-09-26 12:11 UTC, jstourac commented on manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
> +        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.11"},{"name":"ROCm-PyTorch","version":"2.4.1"}]'
We use just major.minor:
```suggestion
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.11"},{"name":"ROCm-PyTorch","version":"2.4"}]'
```

2024-09-26 12:11 UTC, jstourac commented on manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
>          opendatahub.io/notebook-python-dependencies: '[{"name":"ROCm-TensorFlow","version":"2.15"},{"name":"Tensorboard","version":"2.15"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib"
I suppose that the versions here should be also updated.

2024-09-27 04:54 UTC, harshad16 approved these changes
/lgtm
/approve

:+1:

2024-09-27 06:50 UTC, jiridanek commented
/override ci/prow/images

2024-09-27 07:38 UTC, jiridanek commented
/override ci/prow/images

2024-09-27 07:41 UTC, merged